services:

    universal_object_manager:
      class: Youshido\TokenAuthenticationBundle\Service\UniversalObjectManager
      arguments: ['@token_authentication.manager', "%token_authentication.platform%"]

    token_user_provider:
        class: Youshido\TokenAuthenticationBundle\Service\TokenUserProvider
        arguments: ["@universal_object_manager", "@access_token_helper", "%token_authentication.user_model%", "%token_authentication.login_field%"]

    token_authenticator:
        class:  Youshido\TokenAuthenticationBundle\Service\TokenAuthenticator
        arguments: ["@access_token_helper", "%token_authentication.token_field%", "%token_authentication.error_codes%" ]
        public: false

    access_token_helper:
        class: Youshido\TokenAuthenticationBundle\Service\Helper\AccessTokenHelper
        arguments: ["@universal_object_manager", "%token_authentication.token_lifetime%", '%token_authentication.platform%', '%token_authentication.odm_version%']

    token_exception_listener:
        class: Youshido\TokenAuthenticationBundle\Service\Listener\ExceptionListener
        arguments: ["%token_authentication.token_field%"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
